export {
  BOARD_SIZE,
  INITIAL_LENGTH,
  OBSTACLE_MAX,
  OBSTACLE_MIN,
  OPPOSITE,
  VEC,
  addPoint,
  analyze,
  createGame,
  freeNeighbors,
  generateObstacles,
  inBounds,
  isImmediateDeath,
  manhattan,
  nonReverseMoves,
  pointKey,
  reachableCells,
  renderBoardMap,
  resetGame,
  samePoint,
  spawnFood,
  step,
} from "./game.ts";
export { THRESHOLDS, compose } from "./compose.ts";
export {
  DIRECTIONS,
  DIR_EN,
  DIR_LABEL,
  type Candidate,
  type ComposeStep,
  type ComposeTrace,
  type DecideFacts,
  type DecideRequest,
  type DecideResponse,
  type DecisionSource,
  type DecisionTrace,
  type Direction,
  type GameState,
  type GameStatus,
  type Point,
  type Thresholds,
  type TraceAnswer,
  type TraceQuestion,
} from "./types.ts";
